Kotlin. Homework #1. Task #1
WoWaster/spbu-kotlin-homeworks pull request #1
Opened 2022-02-21 19:07 UTC by WoWaster

2022-02-21 19:21 UTC, SpirinEgor requested changes
Папка .idea не должна быть в гите, это же что-то локальное, твоё окружение. Надо добавить её в .gitignore

2022-02-22 06:56 UTC, WoWaster commented
В .gitignore есть ссылка на [доки JB](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839), в которых как раз таки говорится, что в .idea есть файлы, которые стоит класть в гит. К тому же в .idea есть сгенерированный самой IDEA .gitignore со всем, что не нужно в гите.

2022-02-22 09:41 UTC, GirZ0n commented
https://stackoverflow.com/a/54238247

В комментах к тем докам целый холивар развели по поводу того, что нужно игнорировать, а что нет. Лично я использую вот [эту](https://www.toptal.com/developers/gitignore) штуку для генерации `.gitignore` и вот [этот](https://www.toptal.com/developers/gitignore/api/jetbrains+all) конфиг.

2022-02-22 16:28 UTC, SpirinEgor approved these changes

2022-02-22 16:28 UTC, merged