Kotlin. Homework #1. Task #3
WoWaster/spbu-kotlin-homeworks pull request #3
Opened 2022-03-07 16:37 UTC by WoWaster

2022-03-08 07:58 UTC, illided requested changes

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/Actions.kt
> +    fun doAction(list: ArrayDeque<Int>)
А зачем ArrayDeque? Мы же хотим на списке делать операции

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/Actions.kt
> +class SwapAction(private val index1: Int, private val index2: Int) : Action {
В задании просят не поменять элементы местами, а передвинуть элемент с индексом `i` на позицию `j`

Ну и так как операция станет не коммутативна лучше переименовать аргументы

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/Actions.kt
> +        require(list.lastIndex >= index1 && list.lastIndex >= index2) { "Index(-es) out of list bounds" }
А если `index1` и `index2` меньше нуля?

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/PerformedCommandStorage.kt
> +    fun getNumbers(): List<Int> {
А! Вот зачем нужен ArrayDeque! Ну такое... Если кто то захочет расширить твой класс, который работает со списками, а наткнется на работу с очередями будет не очень приятно. Да и получается ты сам себя ограничиваешь.

Если ты хотел так ускорить процесс, то насколько я помню вставка в середину (а еще и в конец и начало) у списка быстрее, так что вообще выигрыша нету :(

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/task_3.kt
> +            input[0] == "exit" -> exitProcess(0)
Воу воу! Давай не будем добавлять в реализацию класса вызов команды которая кладет всю программу :)
Лучше подобного избегать, потому что теории ты потом будешь либо эту логику где то использовать (ООП все таки), либо копировать куски кода и вот таких сюрпризов тебе точно не надо)

2022-03-08 07:58 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/task_3.kt
> +                if (storage.hasActions()) {
Да можно и через `try { ... } catch( ... ) { ... }` сделать тогда

2022-03-08 08:01 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/PerformedCommandStorage.kt
> +    fun getNumbers(): List<Int> {
А еще лучше избегать вот таких гетеров. Лучше сделать две переменные: в одной ты меняешь список, а другая имеет гетер toList()
Вот тут написано подробнее: https://kotlinlang.org/docs/properties.html

2022-03-19 08:26 UTC, illided requested changes
Сейчас мне нравится, мелкие замечания только
Как поправишь поставь review на Егора

2022-03-19 08:26 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/Actions.kt
> +        require(indexFrom in 0..list.lastIndex && indexTo in 0..list.lastIndex) { "Index(-es) out of list bounds" }
Ну или `in list.indices`

2022-03-19 08:26 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/Actions.kt
> +        list.add(indexFrom, list.removeAt(indexTo))
Давай здесь логику разнесем на две строчки, а то читать тяжело

2022-03-19 08:26 UTC, illided commented on src/main/kotlin/homeworks/homework1/task3/PerformedCommandStorage.kt
> +    private val actions = mutableListOf<Action>()
Новую строчку хочется)

2022-03-22 17:10 UTC, SpirinEgor approved these changes

2022-03-22 17:11 UTC, merged